---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos68
    driver_config:
      box: bmcgonigle/centos68
  - name: centos72
    driver_config:
      box: boxcutter/centos72
  - name: ubuntu1404
    driver_config:
      box: boxcutter/ubuntu1404
  - name: debian82
    driver_config:
      box: boxcutter/debian82

suites:
  - name: default
    run_list: 
      - recipe[ixgbevf::default]
    attributes:
